name: coolify-proxy
networks:
  coolify:
    external: true
services:
  traefik:
    container_name: coolify-proxy
    image: traefik:v3.6
    restart: unless-stopped
    extra_hosts:
      - host.docker.internal:host-gateway
    environment:
      - CF_DNS_API_TOKEN=REPLACE_ME
    networks:
      - coolify
    ports:
      - 80:80
      - 443:443
      - 443:443/udp
    healthcheck:
      test: wget -qO- http://localhost:80/ping || exit 1
      interval: 4s
      timeout: 2s
      retries: 5
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /data/coolify/proxy/:/traefik
    command:
      - --ping=true
      - --ping.entrypoint=http
      - --api.dashboard=true
      - --entrypoints.http.address=:80
      - --entrypoints.https.address=:443
      - --providers.file.directory=/traefik/dynamic/
      - --providers.file.watch=true
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --certificatesresolvers.letsencrypt.acme.dnschallenge=true
      - --certificatesresolvers.letsencrypt.acme.dnschallenge.provider=cloudflare
      - --certificatesresolvers.letsencrypt.acme.storage=/traefik/acme.json
      - --certificatesresolvers.letsencrypt-http.acme.httpchallenge=true
      - --certificatesresolvers.letsencrypt-http.acme.httpchallenge.entrypoint=http
      - --certificatesresolvers.letsencrypt-http.acme.storage=/traefik/acme-http.json
      - --certificatesresolvers.letsencrypt-http.acme.email=admin@clientpodium.com
